# Generated by Django 5.1.1 on 2024-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
